version: '3.9'
services:
  nginx-service:
    image: nginx:stable-alpine
    container_name: nginx-container
    ports:
      - "8080:80"
    volumes:
      - ./:/var/www/project
      - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - php82-service
      - postgres-service
    networks:
      - nginx-php81-postgres

  php82-service:
    build:
      context: .
      dockerfile: ./etc/php/Dockerfile
    container_name: php82-container
    ports:
      - "9000:9000"
    volumes:
      - ./:/var/www/project
    networks:
      - nginx-php81-postgres

  postgres-service:
    image: postgres:14-alpine
    container_name: postgres-container
    ports:
      - "5432:5432"
    volumes:
      - ./tmp/postgres:/var/lib/postgresql/tmp
    restart: always
    environment:
      POSTGRES_DB: "diplom"
      POSTGRES_USER: "diplom"
      POSTGRES_PASSWORD: "diplom"
      POSTGRES_HOST_AUTH_METHOD: "password"
      POSTGRES_PASSWORD_ENCRYPTION: "scram-sha-256"
    networks:
      - nginx-php81-postgres

networks:
  nginx-php81-postgres: